<?php

/**
 * @file
 * Support for image media assets in Lightning.
 */

use Drupal\Core\Entity\Display\EntityFormDisplayInterface;
use Drupal\Core\Field\FieldStorageDefinitionInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\entity_browser\Entity\EntityBrowser;
use Drupal\image\Entity\ImageStyle;
use Drupal\entity_browser_generic_embed\OverrideHelper as Override;
use Drupal\entity_browser_image_embed\Plugin\media\Source\Image;
use Drupal\views\ViewEntityInterface;

/**
 * Implements hook_media_source_info_alter().
 */
function entity_browser_image_embed_media_source_info_alter(array &$sources) {
  $sources['image']['input_match']['field_types'] = ['image'];
  Override::pluginClass($sources['image'], Image::class);
}
